version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
       - "5678:5678"
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      - GENERIC_TIMEZONE=Asia/Jakarta
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://103.166.157.22:15678
    volumes:
      - "n8n_volume:/home/node/.n8n"

volumes:
  n8n_volume:
      external: true