metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1
compression_level = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "CHANGE_ME_LOCAL_RPC_SECRET_32_BYTES_MIN"

[s3_api]
s3_region = "garage-local"
api_bind_addr = "[::]:3900"
root_domain = ".s3.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "CHANGE_ME_LOCAL_ADMIN_TOKEN"
metrics_token = "CHANGE_ME_LOCAL_METRICS_TOKEN"

[k2v_api]
api_bind_addr = "[::]:3904"
